dist: bionic
language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
#  - jruby-9.1
  - jruby-9.2
  - jruby-head
jdk:
  - openjdk11
matrix:
  allow_failures:
    - rvm: 3.0
    - rvm: ruby-head
    - rvm: jruby-head
branches:
  only:
      - master
#before_install:
#  - gem update --system
#  - gem --version
addons:
  code_climate:
    repo_token: f6978964f55e6543befb82373651365f8195677816af6ff40ad70c82f7f22f09
