language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-9.0.5.0
  - jruby-9.1.5.0
  - jruby-head
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
matrix:
  exclude:
    - rvm: 2.1.10
      jdk: oraclejdk9
    - rvm: 2.1.10
      jdk: oraclejdk8
    - rvm: 2.2.7
      jdk: oraclejdk9
    - rvm: 2.2.7
      jdk: oraclejdk8
    - rvm: 2.3.4
      jdk: oraclejdk9
    - rvm: 2.3.4
      jdk: oraclejdk8
    - rvm: 2.4.1
      jdk: oraclejdk9
    - rvm: 2.4.1
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: oraclejdk9
    - rvm: ruby-head
      jdk: oraclejdk8
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
branches:
  only:
      - master
addons:
  code_climate:
    repo_token: f6978964f55e6543befb82373651365f8195677816af6ff40ad70c82f7f22f09
