language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.0.5.0
  - jruby-9.1.9.0
  - jruby-head
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
matrix:
  exclude:
    - rvm: 2.4
      jdk: openjdk8
    - rvm: 2.5
      jdk: openjdk8
    - rvm: 2.6
      jdk: openjdk8
    - rvm: ruby-head
      jdk: openjdk8
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
branches:
  only:
      - master
addons:
  code_climate:
    repo_token: f6978964f55e6543befb82373651365f8195677816af6ff40ad70c82f7f22f09
